-- DDL para Sistema de Avaliação de Maturidade Organizacional (NIST CSF)
-- Banco de Dados: Oracle Database
-- Padronização conforme Especificação Técnica CPTM (ET-I-Z-99-99-0199/3-Z99-001)

-- OBS: Utilizei o prefixo "SGSI" para representar o usuário/sistema do banco. 
-- Caso o usuário de banco de dados oficial seja outro (ex: SEC, CVP), basta fazer um Localizar/Substituir no script.

-- 1. Estrutura de RBAC (Controle de Acesso)
CREATE TABLE SGSI_PERFIL (
    id_perfil NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tx_nome VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_SGSI_PERFIL PRIMARY KEY (id_perfil),
    CONSTRAINT UK_SGSI_PERFIL_01 UNIQUE (tx_nome)
);

CREATE TABLE SGSI_USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tx_email VARCHAR2(255) NOT NULL,
    tx_nome VARCHAR2(255) NOT NULL,
    tx_status VARCHAR2(20) DEFAULT 'ATIVO',
    id_perfil NUMBER NOT NULL,
    CONSTRAINT PK_SGSI_USUARIO PRIMARY KEY (id_usuario),
    CONSTRAINT UK_SGSI_USUARIO_01 UNIQUE (tx_email),
    CONSTRAINT FK_SGSI_USUARIO_01 FOREIGN KEY (id_perfil) REFERENCES SGSI_PERFIL(id_perfil),
    CONSTRAINT CK_SGSI_USUARIO_01 CHECK (tx_status IN ('ATIVO', 'INATIVO'))
);

-- 2. Taxonomia NIST CSF 2.0
CREATE TABLE SGSI_FUNCAO (
    id_funcao NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cd_funcao VARCHAR2(10) NOT NULL, -- Código alfanumérico
    tx_nome VARCHAR2(100) NOT NULL,
    tx_cor VARCHAR2(20),
    CONSTRAINT PK_SGSI_FUNCAO PRIMARY KEY (id_funcao),
    CONSTRAINT UK_SGSI_FUNCAO_01 UNIQUE (cd_funcao)
);

CREATE TABLE SGSI_CATEGORIA (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_funcao NUMBER NOT NULL,
    cd_categoria VARCHAR2(20) NOT NULL,
    tx_nome VARCHAR2(255) NOT NULL,
    tx_descricao VARCHAR2(1000),
    CONSTRAINT PK_SGSI_CATEGORIA PRIMARY KEY (id_categoria),
    CONSTRAINT UK_SGSI_CATEGORIA_01 UNIQUE (cd_categoria),
    CONSTRAINT FK_SGSI_CATEGORIA_01 FOREIGN KEY (id_funcao) REFERENCES SGSI_FUNCAO(id_funcao)
);

CREATE TABLE SGSI_SUBCATEGORIA (
    id_subcategoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria NUMBER NOT NULL,
    cd_subcategoria VARCHAR2(20) NOT NULL,
    tx_descricao CLOB NOT NULL,
    tx_status VARCHAR2(20) DEFAULT 'ATIVO',
    CONSTRAINT PK_SGSI_SUBCATEGORIA PRIMARY KEY (id_subcategoria),
    CONSTRAINT UK_SGSI_SUBCATEGORIA_01 UNIQUE (cd_subcategoria),
    CONSTRAINT FK_SGSI_SUBCATEGORIA_01 FOREIGN KEY (id_categoria) REFERENCES SGSI_CATEGORIA(id_categoria),
    CONSTRAINT CK_SGSI_SUBCATEGORIA_01 CHECK (tx_status IN ('ATIVO', 'RETIRADO'))
);

CREATE TABLE SGSI_EXEMPLO_IMP (
    id_exemplo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_subcategoria NUMBER NOT NULL,
    tx_exemplo CLOB NOT NULL,
    CONSTRAINT PK_SGSI_EXEMPLO_IMP PRIMARY KEY (id_exemplo),
    CONSTRAINT FK_SGSI_EXEMPLO_IMP_01 FOREIGN KEY (id_subcategoria) REFERENCES SGSI_SUBCATEGORIA(id_subcategoria)
);

-- 3. Cenários e Avaliações
CREATE TABLE SGSI_CENARIO (
    id_cenario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tx_nome VARCHAR2(255) NOT NULL,
    tx_tipo VARCHAR2(10) NOT NULL, 
    tx_status VARCHAR2(20) NOT NULL, 
    dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dt_efetivacao TIMESTAMP,
    id_usuario_criador NUMBER NOT NULL,
    CONSTRAINT PK_SGSI_CENARIO PRIMARY KEY (id_cenario),
    CONSTRAINT FK_SGSI_CENARIO_01 FOREIGN KEY (id_usuario_criador) REFERENCES SGSI_USUARIO(id_usuario),
    CONSTRAINT CK_SGSI_CENARIO_01 CHECK (tx_tipo IN ('ATUAL', 'ALVO')),
    CONSTRAINT CK_SGSI_CENARIO_02 CHECK (tx_status IN ('EM_ELABORACAO', 'VIGENTE', 'ARQUIVADO', 'PENDENTE_APROVACAO'))
);

CREATE TABLE SGSI_AVALIA_SUBCAT (
    id_avaliacao NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cenario NUMBER NOT NULL,
    id_subcategoria NUMBER NOT NULL,
    tx_status_maturidade VARCHAR2(50),
    tx_prioridade VARCHAR2(10),
    nr_nivel_implementacao NUMBER,
    tx_justificativa CLOB,
    tx_politicas_alvo CLOB,
    tx_praticas_alvo CLOB,
    tx_responsabilidades CLOB,
    CONSTRAINT PK_SGSI_AVALIA_SUBCAT PRIMARY KEY (id_avaliacao),
    CONSTRAINT FK_SGSI_AVALIA_SUBCAT_01 FOREIGN KEY (id_cenario) REFERENCES SGSI_CENARIO(id_cenario),
    CONSTRAINT FK_SGSI_AVALIA_SUBCAT_02 FOREIGN KEY (id_subcategoria) REFERENCES SGSI_SUBCATEGORIA(id_subcategoria),
    CONSTRAINT UK_SGSI_AVALIA_SUBCAT_01 UNIQUE (id_cenario, id_subcategoria),
    CONSTRAINT CK_SGSI_AVALIA_SUBCAT_01 CHECK (tx_status_maturidade IN ('ATENDIDO', 'RAZOAVELMENTE_ATENDIDO', 'PARCIALMENTE_ATENDIDO', 'DEFICITARIAMENTE_ATENDIDO', 'NAO_ATENDIDO')),
    CONSTRAINT CK_SGSI_AVALIA_SUBCAT_02 CHECK (tx_prioridade IN ('ALTA', 'MEDIA', 'BAIXA')),
    CONSTRAINT CK_SGSI_AVALIA_SUBCAT_03 CHECK (nr_nivel_implementacao IN (1, 2, 3, 4))
);

-- 4. Planos de Ação e Evidências
CREATE TABLE SGSI_PLANO_ACAO (
    id_plano NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_avaliacao NUMBER NOT NULL,
    tx_descricao CLOB NOT NULL,
    dt_prazo DATE,
    tx_responsavel VARCHAR2(255),
    tx_status VARCHAR2(20) DEFAULT 'PENDENTE',
    CONSTRAINT PK_SGSI_PLANO_ACAO PRIMARY KEY (id_plano),
    CONSTRAINT FK_SGSI_PLANO_ACAO_01 FOREIGN KEY (id_avaliacao) REFERENCES SGSI_AVALIA_SUBCAT(id_avaliacao),
    CONSTRAINT CK_SGSI_PLANO_ACAO_01 CHECK (tx_status IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO'))
);

CREATE TABLE SGSI_EVIDENCIA (
    id_evidencia NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_avaliacao NUMBER NOT NULL,
    tx_tipo VARCHAR2(50) NOT NULL,
    tx_caminho_url VARCHAR2(1000) NOT NULL,
    dt_inclusao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SGSI_EVIDENCIA PRIMARY KEY (id_evidencia),
    CONSTRAINT FK_SGSI_EVIDENCIA_01 FOREIGN KEY (id_avaliacao) REFERENCES SGSI_AVALIA_SUBCAT(id_avaliacao)
);

-- 5. Propostas de Alteração (Workflow)
CREATE TABLE SGSI_PROP_ALTERACAO (
    id_proposta NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cenario NUMBER NOT NULL,
    id_subcategoria NUMBER NOT NULL,
    id_requerente NUMBER NOT NULL,
    tx_justificativa CLOB NOT NULL,
    tx_valor_anterior CLOB,
    tx_novo_valor CLOB,
    tx_status VARCHAR2(20) DEFAULT 'PENDENTE',
    id_aprovador NUMBER,
    dt_solicitacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dt_aprovacao TIMESTAMP,
    CONSTRAINT PK_SGSI_PROP_ALTERACAO PRIMARY KEY (id_proposta),
    CONSTRAINT FK_SGSI_PROP_ALTERACAO_01 FOREIGN KEY (id_cenario) REFERENCES SGSI_CENARIO(id_cenario),
    CONSTRAINT FK_SGSI_PROP_ALTERACAO_02 FOREIGN KEY (id_subcategoria) REFERENCES SGSI_SUBCATEGORIA(id_subcategoria),
    CONSTRAINT FK_SGSI_PROP_ALTERACAO_03 FOREIGN KEY (id_requerente) REFERENCES SGSI_USUARIO(id_usuario),
    CONSTRAINT FK_SGSI_PROP_ALTERACAO_04 FOREIGN KEY (id_aprovador) REFERENCES SGSI_USUARIO(id_usuario),
    CONSTRAINT CK_SGSI_PROP_ALTERACAO_01 CHECK (tx_status IN ('PENDENTE', 'APROVADA', 'REJEITADA'))
);

-- 6. Trilha de Auditoria
CREATE TABLE SGSI_AUDITORIA_LOG (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario NUMBER,
    dt_hora_utc TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    tx_acao VARCHAR2(50) NOT NULL,
    tx_modulo VARCHAR2(100) NOT NULL,
    tx_entidade_afetada VARCHAR2(100),
    id_registro NUMBER,
    tx_valores_anteriores CLOB,
    tx_novos_valores CLOB,
    tx_ip_origem VARCHAR2(50),
    CONSTRAINT PK_SGSI_AUDITORIA_LOG PRIMARY KEY (id_auditoria)
);

-- Comentários das Tabelas e Campos (Requisito 3.3)
COMMENT ON TABLE SGSI_PERFIL IS 'Tabela de Perfis de Acesso do Sistema NIST';
COMMENT ON COLUMN SGSI_PERFIL.id_perfil IS 'Identificador Numérico exclusivo do registro';
COMMENT ON COLUMN SGSI_PERFIL.tx_nome IS 'Nome do perfil de acesso (ex: Administrador, Editor)';

COMMENT ON TABLE SGSI_USUARIO IS 'Tabela de Usuários com permissão no Sistema NIST';
COMMENT ON COLUMN SGSI_USUARIO.id_usuario IS 'Identificador Numérico exclusivo do registro';
COMMENT ON COLUMN SGSI_USUARIO.tx_email IS 'Email corporativo (usado na autenticacao do Windows)';

-- 7. Seed Inicial
INSERT INTO SGSI_PERFIL (tx_nome) VALUES ('Administrador');
INSERT INTO SGSI_PERFIL (tx_nome) VALUES ('Editor');
INSERT INTO SGSI_PERFIL (tx_nome) VALUES ('Usuário');
INSERT INTO SGSI_PERFIL (tx_nome) VALUES ('Stakeholder');

-- Insert Seed Usuario Admin
INSERT INTO SGSI_USUARIO (tx_email, tx_nome, tx_status, id_perfil) 
VALUES ('marcelo.frota@cptm.sp.gov.br', 'Marcelo Frota', 'ATIVO', (SELECT id_perfil FROM SGSI_PERFIL WHERE tx_nome = 'Administrador'));

-- Insert das Funções do NIST CSF 2.0 
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('GV', 'GOVERNAR', '#F0E68C');
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('ID', 'IDENTIFICAR', '#87CEFA');
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('PR', 'PROTEGER', '#DDA0DD');
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('DE', 'DETECTAR', '#FFA07A');
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('RS', 'RESPONDER', '#FF4500');
INSERT INTO SGSI_FUNCAO (cd_funcao, tx_nome, tx_cor) VALUES ('RC', 'RECUPERAR', '#98FB98');

COMMIT;

